---
title: "Project 1"
format: 
  html:
    self-contained: true
execute:
  echo: true
editor: source
---


## Project Description

In this project, we will be analyzing the [state-by-state spending on kids](https://www.openicpsr.org/openicpsr/project/120914/version/V4/view?path=/openicpsr/120914/fcr:versions/V4&type=project), as generously provided by the [Urban Institute](https://www.urban.org/). Specifically, we will be investigating library spending that has been adjusted for inflation. To get started, see the starter code available on Canvas.

### Pieces That You Will Include

  1. Describe the data using the following table: 
  
|       |                           | 2000 | 2005 | 2010 | 2015 |
|-------|---------------------------|------|------|------|------|
| South | Mean (Standard Deviation) |      |      |      |      |
|       | Median (IQR)              |      |      |      |      |
| West  | Mean (Standard Deviation) |      |      |      |      |
|       | Median (IQR)              |      |      |      |      |

  2. Construct side-by-side boxplots comparing the South and West regions for 2000, 2005, 2010, and 2015. There is code for 2000 available in the starter code; copy, paste, and edit to create the plots for the other years.
  
  3. Describe the distributions. Are they skewed? Do you think there's a difference between the two regions? 
  
  4. Use the appropriate *t* test to determine if there is a difference in library spending between the South and West regions in 2005. Test at the &alpha; = 0.05 level. Include the formal test results (including the formal hypotheses), but in your interpretation, make sure that you explain the results such that a non-statistician can understand.
  
  5. Assess the variance assumption. Test at the &alpha; = 0.05 level. Include the formal test results (including the formal hypotheses), but in your interpretation, make sure that you explain the results such that a non-statistician can understand. Include whether or not the assumption is broken.
  
  6. Assess the normality assumption. In your interpretation, make sure that you explain the results such that a non-statistician can understand. Include whether or not the assumption is broken.
  
  7. Use the appropriate nonparametric test to determine if there is a difference in library spending between the South and West regions in 2005. Test at the &alpha; = 0.05 level. Include the formal test results (including the formal hypotheses), but in your interpretation, make sure that you explain the results such that a non-statistician can understand.
  
  8. Based on your answers to 5 and 6, which test should be reported? Explain why you're choosing the test you're choosing. (Hint: you will either choose the *t* test or the nonparametric test.)
  
  9. Use the appropriate *t* test to determine if there is a difference in library spending between 2005 and 2010 for all states. Test at the &alpha; = 0.05 level. Include the formal test results (including the formal hypotheses), but in your interpretation, make sure that you explain the results such that a non-statistician can understand.
  
  10. Assess the normality assumption. In your interpretation, make sure that you explain the results such that a non-statistician can understand. Include whether or not the assumption is broken.
  
  11. Use the appropriate nonparametric test to determine if there is a difference in library spending between 2005 and 2010 for all states. Test at the &alpha; = 0.05 level. Include the formal test results (including the formal hypotheses), but in your interpretation, make sure that you explain the results such that a non-statistician can understand.
  
  12. Based on your answers to 10, which test should be reported? Explain why you're choosing the test you're choosing. (Hint: you will either choose the *t* test or the nonparametric test.)
 
## Rubric

### 80 points: responses to questions

  - 10 points: table of summary statistics (1)
  - 10 points: box plots (2)
  - 5 points: distribution description (3)
  - 5 points: appropriate *t* test (4)
  - 5 points: variance assumption (5)
  - 5 points: normality assumption (6)
  - 5 points: appropriate nonparametric test (7)
  - 10 points: correct choice between t and nonparametric (8)
  - 5 points: appropriate *t* test (9)
  - 5 points: normality assumption (10)
  - 5 points: appropriate nonparametric test (11)
  - 10 points: correct choice between t and nonparametric (12)
  
### 20 points: paper presentation

  - 5 points: formatting 
  - 5 points: correct grammar and spelling
  - 10 points: clear answers/explanations