---
title: 'STA4173: Project 4 Assignment'
date: 'Last updated: `r Sys.Date()`'
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

## Project Description

In this project, we will be answering questions that show of your new skills in categorical analysis. All questions require a formal hypothesis test. Use &alpha;=0.05 for all tests.

### Meat of Project

You will be putting together a polished document demonstrating your analysis skills based on what you've learned over the past few weeks. The hypothesis testing is only a small piece of your project, though. You must write a cohesive summary from start to finish -- explain what hypotheses you are examining (both in sentence form and in mathematical form) and explain the results. You will write a paper using R Markdown; the paper will be submitted as a .html file to the appropriate dropbox on Canvas. 

### Questions That You Will Answer

  1. The following data cross-classifies votes in the 2000 and 2004 United States presidential elections. Does the sample evidence suggest the proportion of adult Americans who voted for Bush in 2000 is different from the proportion of adult Americans who voted for Bush in 2004?
  
|             | Bush - 2004 | Kerry - 2004 |
|-------------|-------------|--------------|
| **Bush - 2000** | 763         | 65           |
| **Gore - 2000** | 59          | 680          |

  2. The director of library services at a university did a survey of types of books (by subject) in the circulation library. Then they used library records to take a random sample of 1000 books checked out last term and classified the books in the sample by subject. The following data shows the overall percentage of each category in the collection and the number included in the random sample. Is there evidence to suggest that the subject distribution of books in the library does not fit the distribution of books checked out by students?

| Subject         | Percent Owned | Number in Sample |
|-----------------|---------------|------------------|
| Business        | 20%           | 276              |
| Humanities      | 25%           | 219              |
| Natural Science | 30%           | 225              |
| Social Science  | 20%           | 187              |
| Other           | 5%            | 93               |

  3. A randomized experiment was conducted in which patients with coronary artery disease either had angioplasty or bypass surgery. The following data shows incidence of chest pain among the patients 5 years after treatment. Is there evidence to suggest that chest pain is independent of treatment?

|               | Angioplasty | Bypass |
|---------------|-------------|--------|
| Chest Pain    | 111         | 74     |
| No Chest Pain | 402         | 441    |
 
## Rubric

### 75 points: responses to questions

  - 25 points: Q1
  - 25 points: Q2
  - 25 points: Q3
  
### 25 points: paper presentation

  - 5 points: formatting (appropriate section headers, lists, etc.)
  - 5 points: correct grammar and spelling
  - 5 points: organization and flow of presentation  
  - 10 points: clear explanations such that a non-statistician can understand
