---
title: 'STA4173: Project 3'
author: 'Your name here'
date: 'Last updated: `r Sys.Date()`'
output:
  html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

# pull in packages we need
library(tidyverse)
library(palmerpenguins)
library(fastDummies)
library(lindia)
library(car)

# you may need to install some packages first
# use the install.packages() function:
# e.g., install.packages("palmerpenguins")
# note that you will want to run install.packages() outside of your final .Rmd file
# it will not knit if you have an install.packages() line

# NOTE -- you may need additional packages, depending on what is asked of you below :-)

options(scipen = 999)

# pull in penguin dataset - want only complete cases
data <- na.omit(penguins)
```

#### 1. Describe the data (body mass) using the following table: 
  
|                           | Adélie     | Chinstrap    | Gentoo       |
|---------------------------|------------|--------------|--------------|
| Mean (Standard Deviation) |            |              |              |
| Median (IQR)              |            |              |              |

#### 2. Construct side-by-side boxplots comparing the distribution for body mass between the species.
  
#### 3. Describe the distributions. Are they skewed? Do you think there's a difference in body mass between the species? 
  
#### 4. Construct dummy variables for species and sex. (Note that you do not need to type a response here -- just include the code chunk that will create those variables.)
  
#### 5. Construct the regression line that models body mass as a function of bill length, flipper length, species (use Adélie as the reference group), sex, the interaction between bill length and sex, and the interaction between flipper length and sex. 
  
#### 6. Provide brief interpretations for the *b*<sub>i</sub> for the predictors related to species. 

#### 7. Provide a brief interpretation for *b*<sub>0</sub>. Explain why this does or does not make sense.

#### 8. Provide brief interpretations for the interaction terms. (Combine what you know about categorical predictors and interactions.)

#### 9. Perform the appropriate hypothesis test to determine if this is a significant regression line.

#### 10. Perform the appropriate hypothesis tests to determine if the interactions are significant.
  
#### 11. Perform the appropriate hypothesis tests to determine if Gentoo and Chinstrap penguins have significantly different body mass than Adélie penguins.
  
#### 12. Formally assess multicollinearity -- are there any problem predictors?

#### 13. Formally assess potential outliers -- are there any observations we should investigate? Use the table() function to determine the number of potential outliers. (Note: I am not asking you to perform a sensitivity analysis here.)

#### 14. Construct the graph to assess leverage/influence -- are there any observations we should investigate? (Note: I am not asking you to perform a sensitivity analysis here.)
  
#### 15. Construct the graphs to assess the regression assumptions. Are any of the regression assumptions broken? Justify your answer and include statements about the specific graphs.