project:
  type: website

website:
  title: "Biostatistics - Summer 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

